version: '3'

services:
  proxy:
    image: registry.gitlab.com/individual-projects2/service-user-account:servernetwork
    restart: always
    container_name: Account-Proxy
    environment:
      - VIRTUAL_HOST=accountapi.mireu.xyz
    depends_on:
      - api

  api:
    image: registry.gitlab.com/individual-projects2/service-user-account:api
    restart: always
    container_name: Account-API
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: Account-Mongodb
    volumes:
      - Account-MongoDB:/data/db
    environment:
      TZ: Asia/Seoul
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Account

volumes:
  Account-MongoDB:

networks:
  default:
    external:
      name: Container_Proxy_Network